### ISSUE TITLE
Typo in Field-Name

### ISSUE THREAD

**Issue by k-o-n-t-o-r** [Sachs-Media/sevdeskapi#3]
Hey,

ContactModel contains the following field:

`{ "surename": "Peter" } `

Pretty sure it should be renamed to "surname". I know this is a triviality, however, I'm scared my code will break if this is changed later on, which is why I'm reporting it now.

**Comment by eieste** [comment]
Hello,

After a short check of the naming in the SevDesk API I discovered that sevdesk also uses surnames. [https://6083.extern.sevdesk.dev/api/ContactAPI/doc.html#operation/createContact](https://6083.extern.sevdesk.dev/api/ContactAPI/doc.html#operation/createContact)

BUT SevDesk is very inconsistent at this point, because the surname contains the first name

Since such inconsistencies occur more often in the SevDesk API, this API tries to eliminate such errors, but this error is so heavy that it only confuses people if I fix it in the API, but SevDesk keeps its API as it is


But it's also possible that I'm completely wrong at the moment, because the development of this API has been done some time ago.

I will try to extend and improve the API in the near future, because there seems to be a demand for it.
